### ISSUE TITLE
Kill-Update

### ISSUE THREAD

**Issue by philips2955** [dlebansais/Kill-Update#1]
Hello,

I have try to install this version of Kill-update.exe as Administrator but is not working, the icon does not appear and your software don't start 

Have you any issues ?

Thanks

philips

**Comment by philips2955** [comment]
hello

here is the download and tutorial webside :+1: 

[https://www.justgeek.fr/kill-update-bloquer-mises-a-jour-windows-10-57687/](url)

in the zip files don't appear the file "Kill-Update.xml"

Where it is ? 
and why the file "FodyWeavers.xml" ? (what it does?)

Find any issues please

Thanks

philips

**Comment by dlebansais** [comment]
Thanks for reporting this. I'll investigate.

**Comment by dlebansais** [comment]
The latest release at https://github.com/dlebansais/Kill-Update/releases appears to be working fine for me. If you have trouble with administrator mode, you don't have to use it, just follow instructions when you click on "Load at startup".

The zip file just contains source, and FodyWeavers.xml does nothing.
