### ISSUE TITLE
Failed to start after update

### ISSUE THREAD

**Issue by oomek** [dlebansais/Kill-Update#10]
I've noticed one thing. When I disable killupdate and allow the update killupdate won't start after first restart. I do keep launch on startup ticked.

**Comment by dlebansais** [comment]
I tested with the latest update, and while it failed to load on the first restart, it succeeded on the next one. Try to remove from start then load at startup again, and let me know if it still doesn't work.

**Comment by oomek** [comment]
Tried that on a few occasions. It always fails to start on first restart after an update.

**Comment by dlebansais** [comment]
If it works on the next restart, I'm pretty sure there is nothing I can do about it.

**Comment by oomek** [comment]
It's a tough thing to debug, I know. It's not a big deal though as long as you're aware that you need to check if KU is running after updating windows.
