### ISSUE TITLE
How to compile your project from Github source code to the file Kill-Update.exe?

### ISSUE THREAD

**Issue by duy13** [dlebansais/Kill-Update#12]
Hi,
Can you write a step-by-step instruction: how to compile your project from github source code to file **Kill-Update.exe**?

Thanks You!

**Comment by dlebansais** [comment]
+ Install Visual Studio 2019.
+ Clone the repository locally.
+ Double-click `Kill-Update.sln`.
+ Press F5.

**Comment by duy13** [comment]
![Screenshot (221)](https://user-images.githubusercontent.com/10364660/111730830-c79e8180-88a4-11eb-832c-12c82d3c656e.png)

In the Visual Studio 2019 installation step, what do we need to download so that the project can compile?

**Comment by dlebansais** [comment]
.NET desktop development.
