### ISSUE TITLE
32 bit version?

### ISSUE THREAD

**Issue by Suleman-Elahi** [dlebansais/Kill-Update#3]
It works on my office computer which is 64 bit. But it isn't working in 32 bit Windows 10. Can you draft a release for 32 bit systems?

**Comment by dlebansais** [comment]
I uploaded this version that should work on 32-bit too. Please let me know if it does, and I'll add it to the official release.

[KillUpdate.zip](https://github.com/dlebansais/Kill-Update/files/3224530/KillUpdate.zip)

**Comment by Suleman-Elahi** [comment]
Yeah, it is working fine on 1903. Thanks !!
![image](https://user-images.githubusercontent.com/24384996/58490531-f2c55780-818a-11e9-97c7-ceeaf53119bb.png)
