### ISSUE TITLE
Crash after several weeks

### ISSUE THREAD

**Issue by oomek** [dlebansais/Kill-Update#4]
Your app crashes after several weeks of PC sleep/resume cycle. Did Microsoft find a way to kill the killer?

**Comment by dlebansais** [comment]
It's unlikely that Microsoft did something specifically to counter my app. Much more likely, there is a bug in the code. In my own environment I can't test for extended periods of time, but if you have details I can try to fix it.

**Comment by dlebansais** [comment]
I noticed the digital certificate on this app has elapsed. I don't think it makes a difference, but if it does you can try the new release (v1.0.40).

**Comment by oomek** [comment]
Thanks. I'll try and report.

**Comment by FadyQJ** [comment]
App crashes here too.

I leave my pc on for days sometimes weeks and suddenly the app stops working.

The tray icon stays there but the app is not running anymore.

**Comment by dlebansais** [comment]
Unfortunately, I cannot even attempt to reproduce this, my computer restarts every day for reasons outside my control. What I can do is implement logs that can be optionally turned on, and hope I can fix it with what logs people sent me contain.

**Comment by oomek** [comment]
Great, thanks. That's what I was gonna ask for. I'll install it on all my pc's and provide the logs as soon as it crashes

**Comment by dlebansais** [comment]
The new release with logs is live (v1.0.60). I'm closing this bug report. If the problem persist (and it should) please reopen an issue with the log file included.
