### ISSUE TITLE
Heavy CPU usage

### ISSUE THREAD

**Issue by oomek** [dlebansais/Kill-Update#7]
The recent ZombifyMe (try #2) build is very heavy on the cpu. It also causes Defender to go haywire. I have 50% CPU usage combined on 6 core i7

**Comment by oomek** [comment]
There is nothing unusual in the log 
[log.txt](https://github.com/dlebansais/Kill-Update/files/3588429/log.txt)

**Comment by dlebansais** [comment]
Good catch, though it would not be in the logs.
I have fixed it in v1.0.92.
