### ISSUE TITLE
32bit build of latest version

### ISSUE THREAD

**Issue by zeleznika** [dlebansais/Kill-Update#8]
Hi,

Is it possible to build 32bit version of latest version?

Thanks and br, Andrej

**Comment by dlebansais** [comment]
I'm in the process of moving to VS 2019. Also, adding more more quality checks. So not before a little while.

**Comment by dlebansais** [comment]
The latest version is still 64-bits, but all source code is open-source. It should be possible to rebuilt it for 32-bits without much trouble. However, I'm not planning to do this myself.
