### ISSUE TITLE
Scheduled tasks 

### ISSUE THREAD

**Issue by oomek** [dlebansais/Kill-Update#9]
Would you be able to set all scheduled tasks in UpdateOrchestrator branch to disabled? They wake up the computer in the middle of the night. I keep disabling them, but on each update windows is adding new ones and sometimes renabling old ones.

**Comment by dlebansais** [comment]
I take it it's not with the latest pre-release I published a few minutes ago?

**Comment by oomek** [comment]
Does the newly updated app prevent wakeups in some way?

**Comment by oomek** [comment]
I'm not sure if I understand your answer ;)

**Comment by dlebansais** [comment]
I published a new version today as pre-release, but I don't think you could possibly have had time to observe this behavior, so I think you're using the regular release. The new pre-release might fix your issue.

My comment comes from the coincidence between your bug report and the new release that happened almost at the same time, and confused me.

**Comment by dlebansais** [comment]
The latest version should fix all these concerns.

**Comment by oomek** [comment]
Thanks, I'm gonna check it out.
